### ISSUE TITLE
genie does not build with lua-5.4

### ISSUE THREAD

**Issue by belegdol** [bkaradzic/GENie#505]
I just got filed a bug against mame (which is at genie ce9f3c5) in which mame fails to build on Fedora 33:

```
/usr/bin/ld: /tmp/genie.coPNOz.ltrans0.ltrans.o: in function `premake_init':
/builddir/build/BUILD/mame-0.222/3rdparty/genie/build/gmake.linux/../../src/host/premake.c:80: undefined reference to `luaL_register'
/usr/bin/ld: /builddir/build/BUILD/mame-0.222/3rdparty/genie/build/gmake.linux/../../src/host/premake.c:81: undefined reference to `luaL_register'
/usr/bin/ld: /builddir/build/BUILD/mame-0.222/3rdparty/genie/build/gmake.linux/../../src/host/premake.c:82: undefined reference to `luaL_register'
collect2: error: ld returned 1 exit status
make[1]: *** [genie.make:200: ../../bin/linux/genie] Error 1
make: *** [makefile:1652: 3rdparty/genie/bin/linux/genie] Error 2
make: *** Waiting for unfinished jobs....
```
Fedora 33 ships with lua-5.4 which I am guessing is the reason for this.

**Comment by bkaradzic** [comment]
So what?

GENie ships with Lua 5.3.0 source: https://github.com/bkaradzic/GENie/tree/master/src/host/lua-5.3.0

Use that instead.
